spring.application.name=MiniProject2

spring.datasource.url=jdbc:mysql://localhost:3306/practice
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#smtp password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vsabale316@gmail.com
spring.mail.password=gbig izqn 4454 shkt
spring.mail.properties.mail.smtp.starttls.enable=true